<?php
defined('BASEPATH') OR exit('No direct script access allowed');

require_once(APPPATH.'third_party/tcpdf/tcpdf.php');

class MY_Tcpdf extends TCPDF {
    public $printed;
    public $HeaderText;

    public function __construct() {
        parent::__construct();
    }

    public function Header() {
        $this->SetLeftMargin(10);
        $this->SetTopMargin(0);
        $this->SetRightMargin(10);
       
        // Print dynamic control number in header
        if (!empty($this->HeaderText)) {
             // Remove the default header line
            $this->SetY(5); // Set Y position
            $this->SetFont('helvetica', 4);
            $this->Cell(5, 2, $this->HeaderText, 0, 1, 'L');
        }
    }

    // Function to draw checkbox
    public function DrawCheckbox($x, $y, $size, $checked = false) {
        $this->SetFillColor(255, 255, 255); // Fill color
        $this->SetDrawColor(0, 0, 0); // Border color
        $this->Rect($x, $y, $size, $size, 'DF'); // Draw the checkbox

        if ($checked) {
            $this->SetDrawColor(0, 0, 0); // Checkmark color
            $this->SetLineWidth(1);
            $this->Line($x + 2, $y + $size - 2, $x + $size - 2, $y + 2); // Diagonal line
            $this->Line($x + 2, $y + 2, $x + $size - 2, $y + $size - 2); // Diagonal line
        }
    }

    public function Footer() {
        $this->SetY(-15); // Position from bottom
        $this->SetFont('helvetica', 'I', 8);

        // Page number
        $pageNumber = $this->getAliasNumPage();
        $totalPages = $this->getAliasNbPages();
        $this->Cell(0, 10, 'Page '.$pageNumber.' of '.$totalPages, 0, 0, 'C');

        //date
        $dateTime = new DateTime('now', new DateTimeZone('Asia/Manila'));
        // Format the date and time
        $date = $dateTime->format('Y.m.d H:i:s');

        // Add printed by info, if available
        $name = isset($this->printed) ? $this->printed : 'Unknown';
        $this->Cell(0, 10, 'Generated by: '.$name.' '.$date, 0, 0, 'R');
    }

    // Method to add watermark
    public function addWatermark($text) {
        // Set transparency
        $this->SetAlpha(0.3);

        // Set watermark text properties
        $this->SetFont('helvetica', 'B', 30);
        $this->SetTextColor(150, 150, 150);

        // Add watermark text to the page
        $this->RotatedText(20, 200, $text, 45);

        // Restore alpha to default
        $this->SetAlpha(1);
    }

    // Rotated text
    public function RotatedText($x, $y, $txt, $angle) {
        $this->StartTransform();
        $this->Rotate($angle, $x, $y);
        $this->Text($x, $y, $txt);
        $this->StopTransform();
    }
}
